services:
  nginx:
    container_name: flask_nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - flask-network

  app:
    container_name: flask_app
    build: .
    volumes:
      - ./src:/app/src
    environment:
      - FLASK_DEBUG=on
    networks:
      - flask-network

  db:
    container_name: flask_mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - flask-network

networks:
  flask-network:
      driver: bridge

volumes:
  db_data: